link-git/Cargo.toml
link-git/t/Cargo.toml
radicle-git-ext/Cargo.toml
radicle-git-types/Cargo.toml
radicle-surf/Cargo.toml

The git2 crate has moved forward and is now at version 0.15.0 while the dependencies in radicle-git were using 0.13.
Bump the dependencies to version 0.15.0.
Closes #14

meta: update to git2-0.15.0

---

git-ref-format/core/src/lit.rs
nix/sources.json
radicle-git-types/src/urn.rs
radicle-surf/src/tree.rs
radicle-surf/src/vcs.rs

rust-1.64 was announced[0].
Update the nix sources to pick up the latest stable. This update requires some fixes suggested by clippy.
[0]: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html

nix: rust-1.64

---

.github/workflows/ci.yaml
radicle-surf/examples/diff.rs
radicle-surf/src/commit.rs
radicle-surf/src/revision.rs
radicle-surf/src/vcs/git.rs
radicle-surf/src/vcs/git/commit.rs
radicle-surf/src/vcs/git/namespace.rs
radicle-surf/src/vcs/git/reference.rs
radicle-surf/src/vcs/git/repo.rs
radicle-surf/src/vcs/git/stats.rs
radicle-surf/src/vcs/git/tag.rs

This is to fix issue #5 and also:
- fix CI errors on main branch.
~~- fix Rust 1.64.0 clippy warnings.~~ It was fixed by https://github.com/radicle-dev/radicle-git/pull/19

radicle-surf: convert git2::Oid to radicle_git_ext::Oid

---

radicle-git-ext/t/Cargo.toml
radicle-git-ext/t/src/gen.rs
radicle-git-ext/t/src/gen/urn.rs
radicle-git-ext/t/src/lib.rs

Addresses #8.
Ported from https://github.com/radicle-dev/radicle-link.
Note that the `Strategy` returns the radicle-git `Oid`type but it uses `git2::Oid` internally to generate it
since our `Oid` does not expose the `hash_object` and `zero` functions.

radicle-git-ext/t: Port `gen_oid*` generator methods

---

git-ref-format/macro/src/lib.rs
git-ref-format/src/lib.rs
git-ref-format/t/src/tests.rs

Add a `qualified!` macro to the set of git-ref-format macros. This allows the construction of a `refs/<cat>/<name>` reference from a string literal.

git-ref-format: qualified macro

---

git-ref-format/core/src/cbor.rs
git-ref-format/core/src/deriv.rs
git-ref-format/core/src/name.rs
git-ref-format/core/src/serde.rs
git-ref-format/t/src/tests.rs

The namespace functions can read confusingly:
* `namespaced` - the naming sounds like it is namespacing the input, when in fact it is ensuring that the input is namespaced.
* `add_namespace` - can be read as adding the namespace to the end of a ref, when in fact it is placed at the beginning.
Change the naming, respectively, to:
* `to_namespaced` - this uses the conversion naming convention detailed here[[0]].
* `with_namespace` - reads as plainly namespacing the ref string.
[0]: https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv

git-ref-format: rename namespace functions

---

git-ref-format/Cargo.toml
git-ref-format/core/Cargo.toml
git-ref-format/macro/Cargo.toml

Attempting to publish these crates results in errors that the `description` field is missing and that the path dependencies do not specify versions.
Add the `description` and `keywords` fields to `git-ref-format-core`, `git-ref-format-macro` and `git-ref-format`.
Add the versions for the dependent crates.
These are now publish: https://crates.io/search?q=git-ref-format

git-ref-format: prepare git-ref-format crates for publishing

---

radicle-surf/docs/refactor-design.md
radicle-surf/src/commit.rs
radicle-surf/src/object/tree.rs
radicle-surf/src/vcs.rs
radicle-surf/src/vcs/git/repo.rs
radicle-surf/t/src/git.rs

This is a small patch for issue #27:
- Detect renames in Diff by default. (Fix issue #35)
- Remove Vcs trait.
- Move `history()` to be a regular method of RepositoryRef.
- Update design doc.

radicle-surf: refactor the design: part 3

---

git-trailers/Cargo.toml
git-trailers/src/lib.rs

OwnedTrailer was lacking a Debug impl and access to its values.
Add a Debug derivation for OwnedTrailer and OwnedToken. Make token and values public. Add Deref implementation for OwnedToken.

git-trailers: improve usage of OwnedTrailer

---

link-git/src/odb/index.rs
link-git/src/protocol/upload_pack.rs
link-git/src/protocol/upload_pack/legacy.rs
nix/sources.json
nix/sources.nix
radicle-git-ext/src/blob.rs
radicle-macros/src/lib.rs
radicle-surf/src/vcs/git.rs

Update to rust-1.65[[0]].
All hail our new GATs overlord!
[0]: https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html

nix: update to rust-1.65

---

Cargo.toml
git-commit/Cargo.toml
git-commit/src/author.rs
git-commit/src/headers.rs
git-commit/src/lib.rs
git-commit/t/Cargo.toml
git-commit/t/src/commit.rs
git-commit/t/src/integration.rs
git-commit/t/src/lib.rs
test/Cargo.toml

Porting the commit code that is found in heartwood[[0]]. It represents a parsed git commit object -- sans the id for the commit itself.
[0]: https://github.com/radicle-dev/heartwood/blob/16b22d9178fa6a1aaf2ecb01ec97e067399c5286/radicle/src/git.rs#L392-L575

git-commit: introduce git-commit crate

---

radicle-surf/benches/last_commit.rs
radicle-surf/examples/diff.rs
radicle-surf/src/vcs/git/repo.rs
radicle-surf/t/src/git.rs

Fix issue #9 .
- Replaces the existing Repository::new() with ::open() that supports searching parent directories. If we deem that `::new()` should be kept, we can add it back that simply calls `open()` internally.

search parent directories in Repository::open

---

git-ref-format/core/src/deriv.rs
git-ref-format/core/src/name.rs
git-ref-format/core/src/name/iter.rs
git-ref-format/core/src/refspec.rs
git-ref-format/core/src/refspec/iter.rs
git-ref-format/t/src/tests.rs
radicle-surf/src/commit.rs
radicle-surf/src/git/branch.rs
radicle-surf/src/git/glob.rs
radicle-surf/src/git/namespace.rs
radicle-surf/src/git/repo.rs
radicle-surf/src/git/tag.rs
radicle-surf/t/src/git.rs

The main change is described in https://github.com/radicle-dev/radicle-git/commit/e4853c10bcc5606ea419f07b6f043a4b280b88b3 but required a few changes in `git-ref-format`.

radicle-surf: Namespace using RefString

---

radicle-surf/src/git/repo.rs
radicle-surf/src/git/repo/iter.rs
radicle-surf/src/git/tag.rs
radicle-surf/src/revision.rs

The `tag_names` and `branch_names` functions use the `Tags` and
`Branches` functions which require to go through their `TryFrom`
instances. This can be expensive, in the case of `Tags` especially.
Add `TagNames` and `BranchNames` iterators that only return the names
of the tags and branches, respectively.
This requires to change the definition of Revisions, where the
NonEmpty branch list is now foregone and there references are
collected in a BTreeSet to ensure ordering.

radicle-surf: iterator for names

---

git-ref-format/Cargo.toml
git-ref-format/core/Cargo.toml
git-ref-format/core/src/deriv.rs
git-ref-format/core/src/lit.rs
git-ref-format/core/src/name.rs
git-ref-format/core/src/name/iter.rs

Since this package is not intended for radicle-link anymore, the feature flag and the literals are removed.
FIxes #58

git-ref-format: remove link-literals feature

---

radicle-surf/Cargo.toml
radicle-surf/examples/browsing.rs
radicle-surf/src/file_system.rs
radicle-surf/src/file_system/directory.rs
radicle-surf/src/git/repo.rs
radicle-surf/src/object.rs
radicle-surf/src/object/blob.rs
radicle-surf/src/object/tree.rs
radicle-surf/t/src/file_system.rs
radicle-surf/t/src/git.rs

Change the inner value of a File and Directory to be generic. This allows the inner value to be an Oid, if it's not resolved. If the content are resolved they will be FileContent & Entries respectively.
This allows the writing of nice helper functions such as `fold`, `try_fold`, and `traverse`.

radicle-surf: make directory and file contents generic

---

radicle-surf/src/diff.rs

Remove the `Diff::diff` as it is unused.

radicle-surf: remove diff function

---

radicle-surf/src/commit.rs
radicle-surf/src/git/glob.rs
radicle-surf/src/git/repo.rs
radicle-surf/src/revision.rs
radicle-surf/t/src/git/namespace.rs
radicle-surf/t/src/git/reference.rs
radicle-surf/t/src/git/threading.rs

This patch changes the glob module in a couple of ways, outlined below.
The first change is the use of PatternString in the constructor functions. This removes the fallibility of the constructors. This meant that the tests changed to use the `pattern!` macro instead.
The second change is splitting out the `Glob<Branch>` methods into `Glob<Local>` and `Glob<Remote>`. This means that the local and remote globs can be constructed separately, and are then combined via the `branches` and `and` methods.

radicle-link: refactor glob

---

git-commit/Cargo.toml
git-commit/src/lib.rs
git-commit/t/src/commit.rs

Fixes #73 
There was an issue where the trailers were not properly separated from the commit message itself. In fact, a new line is not added if there are not trailers either.
Add a fix to add a newline after the commit message. Also adding test cases to test 0, 1, or 2 trailers in a git commit.

git-commit: fix to lack of newline separation

---

radicle-surf/examples/browsing.rs
radicle-surf/examples/diff.rs
radicle-surf/src/file_system/directory.rs
radicle-surf/src/git.rs
radicle-surf/src/git/history.rs
radicle-surf/src/git/repo.rs
radicle-surf/src/git/stats.rs
radicle-surf/src/source/commit.rs

To have a clear separation of which are public functions and which are private functions, two `impl Repository` blocks are created.
This lead to some refactoring of names and inclusion of helper functions, removing the need for the `git2_repo` function.
The `get_commit_stats` function seemed off, since the `Stats` in this case are to do with the repository. Thus, it does not take a commit anymore and instead uses the `head` commit to calculate the repository's `Stats`.

radicle-surf: refactor repo

---

radicle-surf/README.md
radicle-surf/examples/browsing.rs
radicle-surf/src/diff.rs
radicle-surf/src/file_system/directory.rs
radicle-surf/src/lib.rs
radicle-surf/src/source/object/tree.rs
radicle-surf/t/src/file_system.rs
radicle-surf/t/src/lib.rs

- Started to update doc for this crate.
- Moved a doc test in a real test case.
- Found one test file `file_system` was not enabled.  Enabled it.
- Fixed a couple bugs after the above test was enabled.

Enable tests in file_system

---

radicle-surf/examples/browsing.rs
radicle-surf/src/git.rs
radicle-surf/src/git/history.rs
radicle-surf/src/git/repo.rs
radicle-surf/t/src/file_system.rs
radicle-surf/t/src/git/code_browsing.rs
radicle-surf/t/src/git/last_commit.rs
radicle-surf/t/src/git/rev.rs

When I'm playing around `heartwood/radicle-httpd` to use the latest `radicle-git/radicle-surf`, I found some quirks of the API (one is [`History::new()` cannot take `&sha`](https://github.com/radicle-dev/heartwood/blob/ca69fdc4fa532aef074b62fb9a765e38d1db298b/radicle-httpd/src/api/v1/projects.rs#L144)), which motivated this patch.
- Added a generic impl for &Revision
- Updated ToCommit for easier usage.

refactoring Revision and ToCommit traits

---

git-ref-format/core/src/serde.rs
git-ref-format/t/Cargo.toml
git-ref-format/t/src/properties/name.rs
git-ref-format/t/src/properties/pattern.rs
test/test-helpers/src/roundtrip.rs

When deserializing through `serde_json::from_value` the following
error would occur:
```
panicked at 'called Result::unwrap() on an Err value: Error("invalid
type: string "master", expected a borrowed string", line: 0, column:
0)'
```
To fix this it is necessary for the Deserialize implementations to
deserialize into an owned String and convert from there.
While attempting to test this the `Qualified` and `Namespaced`
implementations were not able to be used:
```
error: implementation of `serde::de::Deserialize` is not general enough
--> git-ref-format/t/src/properties/name.rs:86:9
|
86 |         roundtrip::json_value(qualified);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `serde::de::Deserialize` is not general enough
|
= note: `Qualified<'_>` must implement …
```

git-ref-format: fix to deserialization

---

radicle-surf/src/diff.rs
radicle-surf/src/file_system/directory.rs
radicle-surf/src/source/commit.rs
radicle-surf/src/source/object/blob.rs
radicle-surf/src/source/object/tree.rs
radicle-surf/t/src/git/diff.rs
radicle-surf/t/src/lib.rs
radicle-surf/t/src/source.rs

The http-api code expects the 'path' serialized field to be the full path for trees, tree entries, and blobs, i.e. the path where it is located concatenated with the name of the entry.

surf: fix path serialization for tree and blob

---

radicle-surf/src/file_system/directory.rs
radicle-surf/src/git/history.rs
radicle-surf/src/git/repo.rs
radicle-surf/src/source/object/blob.rs
radicle-surf/src/source/object/tree.rs
radicle-surf/t/src/file_system.rs
radicle-surf/t/src/git/code_browsing.rs
radicle-surf/t/src/git/last_commit.rs
radicle-surf/t/src/source.rs

This is motivated by my [attempt](https://github.com/radicle-dev/heartwood/pull/149) to use the new `radicle-surf` API in `heartwood/radicle-httpd`.  The main changes are:
1. Refactored `Tree` and `Blob` so that they represent the "contents" without embedding the path or the file name. In contrast, `Directory` and `File` include their own `path` and `name`.
2. Provided `repo.tree()`, `repo.blob()`, `repo.directory()` and `repo.file()` methods. 
3. Provided `directory.last_commit()` to show that `Directory` can provide everything a user might wanted from a `Tree`, although in a more "lazy" style.
The immediate goal is to allow the user to try out the `tree` and `blob` methods since it seems they feel familiar with them, and less confused comparing with `Directory` and `File`. Once people …

refactor Tree, Blob, Directory and File

---

git-commit/src/author.rs

Previously, there was no way to access the seconds and offset fields of the Time type.
Add methods for accessing the fields.

git-commit: add Time accessors

---

radicle-surf/src/git/repo.rs
radicle-surf/src/source/commit.rs

The `stats` method always provided the stats at the `head` of the repository.
Instead, allow the revision to be optionally specified and default to head if not provided.

surf: stats for a given revision

---

radicle-surf/src/object/tree.rs
radicle-surf/t/src/source.rs

Comparing tree entries would only take into account their names. While this is useful, it is also useful to compare by their entry kind first, where trees take precedence over blobs.

surf: fix comparison of tree entries

---

radicle-surf/src/object.rs

The Error type is no longer used thanks to the clean up of the Tree and Blob constructions now being exposed through Repository.
Remove the Error type and clean up the imports as a result.

surf: remove object::Error

---

radicle-surf/src/fs.rs
radicle-surf/src/object/tree.rs
radicle-surf/src/repo.rs
radicle-surf/t/src/file_system.rs

It is not clear at this point that `Directory` and `File` needs a `last_commit()` method as the user likely has the context to call `repo.last_commit()` to achieve the goal. As it is easier to add things than to deleting things in future, we deemed it is better not to have them at this point.
Also renamed "id" to "tree_id" in Directory and "blob_id" in File so that their meanings are clearer.
This is to address one problem / FIXME mentioned in https://github.com/radicle-dev/radicle-git/issues/91#issuecomment-1370801069 . The diff also clarifies more between `Tree`/`Blob` and `Directory`/`File`.

remove last_commit() in Directory and File

---

radicle-surf/docs/refactor-design.md
radicle-surf/src/history.rs

This is to resolve the issue #27 . The aim is to wrap up the design doc. For the next step in documentation, I think we can focus on the doc comments visible in `cargo doc`.

update the design doc

---

.github/workflows/ci.yaml
radicle-surf/src/error.rs
radicle-surf/src/lib.rs
radicle-surf/src/repo.rs

This is to solve issue #91. 
Moved `Error` in `repo.rs` out into a crate level `Error` in `error.rs`. Repository specific errors are wrapped by the `crate::Error` as well.
Also, the latest Rust 1.67.0 causes many lint errors with `println!`. I am changing `lint` to stay with Rust `1.66.1` to avoid unnecessary lint errors. We can move to Rust 1.67.0 or `stable` via a later PR.

radicle-surf: refactoring the error type

---

radicle-surf/src/branch.rs
radicle-surf/src/commit.rs
radicle-surf/src/diff.rs
radicle-surf/src/glob.rs
radicle-surf/src/history.rs
radicle-surf/src/lib.rs
radicle-surf/src/repo.rs
radicle-surf/src/revision.rs
radicle-surf/src/tag.rs
radicle-surf/t/src/commit.rs

This patch focuses on the front page of `cargo doc` output and a few related changes. This is part of the effort for solving https://github.com/radicle-dev/radicle-git/issues/100.

radicle-surf: Update doc comments.

---

radicle-surf/src/blob.rs
radicle-surf/t/src/source.rs

Avoid copying the bytes content of a `git2::Blob` by introducing a generic parameter on Blob.
The parameter can either be a `BlobRef` or `BlobVec`, by using the `to_owned` function.
`BlobRef` and `BlobVec` both implement `AsRef` and `Deref` for `[u8]` to make them easier to use and allows the definition of generic functions on `T`.

surf: borrowed and owned Blob content

---

radicle-surf/src/diff.rs
radicle-surf/src/diff/git.rs
radicle-surf/t/src/diff.rs

This is to solve issue #108 .
- Moved `eof` into `DiffContent::Plain`  as it only makes sense to plain text diffs. This changes the serialization of `Diff` and `DiffContent` but it's limited to only `eof` element.
- Added a variant in `EofNewLine` enum: `NoneMissing` that is used when both the old file and the new file have a EOF new line, or for a newly `Added` file etc.

radicle-surf: refactoring EofNewLine

---

git-ref-format/Cargo.toml
git-ref-format/core/CHANGELOG.md
git-ref-format/core/Cargo.toml
git-ref-format/macro/CHANGELOG.md
git-ref-format/macro/Cargo.toml
radicle-git-ext/Cargo.toml
radicle-surf/Cargo.toml

This is also related to #100 .
The CHANGELOG.md is basically a list of git commit for the version. Not sure if it's the best format but it's a start.

git-ref-format: bump up version and add CHANGELOG.md

---

radicle-surf/Cargo.toml
radicle-surf/src/error.rs
radicle-surf/src/lib.rs
radicle-surf/src/repo.rs
radicle-surf/t/src/code_browsing.rs

Work related to #100 .
- Clean up some doc comments and add a missing test case.
- Use `crates.io` for specifying the internal crate dependencies. (Removing `path`)

radicle-surf: update docs and add test for commit signature

---

git-commit/src/lib.rs

This diff is triggered by a test failure in PR https://github.com/radicle-dev/heartwood/pull/280 .
~~However, it is not clear to me what exactly format we want for a commit. I'm adding some comments in the code.~~
This diff morphs into a simple refactoring for a check that I think is useless.

git-commit: remove useless check in to_string()

---

git-commit/Cargo.toml
git-commit/src/lib.rs
git-commit/src/trailers.rs
git-commit/t/Cargo.toml

Supersedes #116, as it uses `git2`'s functionality for parsing commit trailers.
The git-trailers crate depends on parsing logic using nom. This is a heavy dependency for something that can be done using git2.
Remove the dependency of git-trailers in git-commit and localise the trailer types -- using git2 to parse the trailers out of the git commit message.

git-commit: remove dependency on git-trailers

---

radicle-surf/src/diff.rs

This allows to get the latest path of a `FileDiff`, directly from `radicle_surf`
Usage example: In the `radicle-httpd` diff endpoints we want to add the blobs of the files that are involved in a diff, and this way we could do a `repo.blob(commit, file_diff.path())` to get the `path` quickly.

surf: Add `FileDiff::path` method

---

radicle-surf/src/diff.rs

Fix Modification doc typo

---

radicle-surf/src/diff.rs
radicle-surf/src/diff/git.rs

Put the Diff type in lines with its associated types by opening it up to construction by crate consumers.  The existing associated types have all their fields public.
Open construction up by making the `Diff::insert_*` methods public and updating the Diff's stats manually.  `Diff::stat` correctness is covered by existing tests.

surf: Open Diff to custom construction

---

radicle-surf/src/diff.rs
radicle-surf/src/diff/git.rs
radicle-surf/t/src/diff.rs

In some cases a moved file can also be modified and in these cases there will be a diff as well as new Oid's for the two sides of the diff.
Add DiffFile to the Moved type, changing the insert_moved method to accept the DiffFile's and the DiffContent.
When serializing a Moved, if the old and the new are the same then the serialization of the diff files and content are skipped -- same as the old behaviour. Otherwise, the two sides are serialized along with the content.
Fixed #140 
cc @sebastinez how will this affect radicle-interface/radicle-httpd for showing diffs for moved files?

Improved `Moved`

---

radicle-surf/src/diff.rs
radicle-surf/src/diff/git.rs
radicle-surf/t/src/diff.rs

This allows us to know the blob oid of a moved or copied file, even when no diff is available.

surf: Add `DiffFile` to `FileDiff::Copied` and `FileDiff::Moved`

---

radicle-surf/src/diff.rs
radicle-surf/src/diff/git.rs
radicle-surf/t/src/diff.rs

This allows us to get the additions and deletions for each file in a diff.

surf: Add `stats` property to each `DiffContent::Plain`

---

radicle-surf/src/blob.rs
radicle-surf/src/repo.rs

The current `blob` function is limited to always associating a Blob with a Commit.
Expose `BlobRef` through a `blob_ref` method, and add useful methods and serialization to it.

surf: expose BlobRef
